version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    container_name: fm_postgres
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - fm_postgres:/var/lib/postgresql/data

volumes:
  fm_postgres: