import type { Metadata } from 'next'

import { SessionProvider } from 'next-auth/react'
import { auth } from '@/src/auth'
import { Navbar } from '@/src/components/navbar';
import { ColorSchemeScript, createTheme, MantineProvider } from '@mantine/core';
import { Notifications } from '@mantine/notifications';

// Import styles of packages that you"ve installed.
// All packages except `@mantine/hooks` require styles imports
import '@mantine/core/styles.css';
import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

const theme = createTheme({
	/** Put your mantine theme override here */
});

export default async function RootLayout({children}: { children: React.ReactNode }) {
	const session = await auth();

	return (
		<html lang="en">
			<head>
				<ColorSchemeScript />
			</head>
			<body>
				<SessionProvider session={session}>
					<MantineProvider theme={theme}>
						<Notifications className="w-[200px] absolute" right={20} bottom={20} />
						<Navbar />
						{children}
					</MantineProvider>
				</SessionProvider>
			</body>
		</html>
	);
}
