# https://docs.github.com/en/actions/using-workflows/reusing-workflows
name: PR/Push update

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  linting:
    uses: ./.github/workflows/linting.yml

  codeql:
    needs: linting
    if: ${{ needs.linting.result == 'success' }}
    uses: ./.github/workflows/codeql.yml
