# https://docs.github.com/en/actions/using-workflows/reusing-workflows
name: PR/Push update

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  linting:
    uses: ./.github/workflows/linting.yml

  codeql:
    needs: linting
    if: ${{ needs.linting.result == 'success' }}
    uses: ./.github/workflows/codeql.yml

  build:
    needs: linting
    if: ${{ needs.linting.result == 'success' }}
    uses: ./.github/workflows/build.yml
